name: RMCMaterialLoadingPlugin
version: 1.0
main: cn.huyast111.rmc.RMCMaterialLoadingPlugin
api-version: 1.8.8
description: 材质包加载插件
author: huyast111

commands:
  czb:
    description: 材质包加载命令
    usage: /czb [reload|config|send|prompt]
    permission: rmc.use
    
permissions:
  rmc.use:
    description: 允许玩家使用基本命令
    default: true
  rmc.admin:
    description: 允许玩家使用管理员命令
    default: op 